FROM node:latest
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=/node_modules/.bin:$PATH
WORKDIR /app

COPY front-end/package.json /app/
COPY front-end/yarn.lock /app/

RUN yarn install --modules-folder=/node_modules --frozen-lockfile --non-interactive

EXPOSE 3000

CMD ["yarn", "start"]