FROM python:3.10-slim

RUN mkdir /app
WORKDIR /app

COPY back-end/requirements.txt /app/
RUN pip install -r requirements.txt

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload" ]
